package BankServer;


/**
* BankServer/bankHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Tuesday, April 21, 2015 3:28:52 PM IST
*/

abstract public class bankHelper
{
  private static String  _id = "IDL:BankServer/bank:1.0";

  public static void insert (org.omg.CORBA.Any a, BankServer.bank that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BankServer.bank extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BankServer.bankHelper.id (), "bank");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BankServer.bank read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_bankStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BankServer.bank value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BankServer.bank narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankServer.bank)
      return (BankServer.bank)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankServer._bankStub stub = new BankServer._bankStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BankServer.bank unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankServer.bank)
      return (BankServer.bank)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankServer._bankStub stub = new BankServer._bankStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
