package BankServer;


/**
* BankServer/bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Tuesday, April 21, 2015 3:28:52 PM IST
*/

public interface bank extends bankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface bank
