package BankServer;

/**
* BankServer/bankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Tuesday, April 21, 2015 3:28:51 PM IST
*/

public final class bankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankServer.bank value = null;

  public bankHolder ()
  {
  }

  public bankHolder (BankServer.bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankServer.bankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankServer.bankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankServer.bankHelper.type ();
  }

}
