package BankServer;


/**
* BankServer/bankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Tuesday, April 21, 2015 3:28:52 PM IST
*/

public interface bankOperations 
{
  String signIn (String userid, String password);
  String getAccounts (String accnum);
  double getBalance (String account);
  String deposit (String account, String amount, String userid);
  String withdraw (String account, String amount, String userid);
  String getInfo (String userid);
  String addUser (String userid, String username, String mobile, String adress, String email, String usertype);
  String addAccount (String userid, String accNo, String initDeposit, String accType);
  String getAccountList (String userid);
  void shutdown ();
} // interface bankOperations
